/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'html',
      value: `
        <aside class="linsi-sidebar-credit" aria-label="Créditos">
          <span class="linsi-sidebar-credit__eyebrow">Criado por</span>
          <strong class="linsi-sidebar-credit__name">Bea Miranda</strong>
          <span class="linsi-sidebar-credit__title">Product Designer</span>
          <a
            class="linsi-sidebar-credit__link"
            href="https://linkedin.com/in/bmirandaq"
            target="_blank"
            rel="noopener noreferrer"
          >
            LinkedIn
          </a>
        </aside>
      `,
      defaultStyle: false,
    },
  ],
};

export default sidebars;
